version: '3.8'
services:
  front:
    build: ./front
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:${BACK_PORT}/api
    volumes:
      - ./front:/app
      - /app/node_modules

  back:
    build:
      dockerfile: Dockerfile
      context: ./back
    environment:
      - BACK_PORT=${BACK_PORT}
    ports:
      - 3000:${BACK_PORT}
    volumes:
      - ./back:/app