app:
  name: "chat"

server:
  host: "localhost"
  port: "3000"

db:
  username: "name"
  password: "pass"
  host: "db"
  port: "5432"
  name: "chat"

jwt:
  secret: "azerty123"

front:
  host: "url"
